# Generated by 2sc from function 'macres' (2026-08-12 12:36:39).
# Hardened: finds the latest COMPLETE backup set across both recovery folder
# names and restores it from the correct first span (-00-00).
function macres {
    $mrauto = 'F:\backup\windowsapps\installed\reflect\mrauto.exe'
    if (-not (Test-Path -LiteralPath $mrauto -PathType Leaf)) {
        Write-Host "macres: mrauto.exe not found: $mrauto" -ForegroundColor Red
        return
    }

    $candidateFolders = @('F:\win11recovery', 'F:\windows11recovery')
    $entryPoints = @()
    foreach ($folder in $candidateFolders) {
        if (-not (Test-Path -LiteralPath $folder -PathType Container)) { continue }
        $entryPoints += @(Get-ChildItem -LiteralPath $folder -File -ErrorAction SilentlyContinue | Where-Object {
            $_.Extension -eq '.mrimg' -or $_.Name -match '-00-00\.mrimgx$'
        })
    }

    if ($entryPoints.Count -eq 0) {
        $fallback = @()
        foreach ($folder in $candidateFolders) {
            if (-not (Test-Path -LiteralPath $folder -PathType Container)) { continue }
            $fallback += @(Get-ChildItem -LiteralPath $folder -File -ErrorAction SilentlyContinue | Where-Object {
                $_.Extension -in @('.mrimg', '.mrimgx')
            })
        }
        $fallback = @($fallback | Sort-Object LastWriteTime -Descending | Select-Object -First 1)
        if ($fallback.Count -eq 0) {
            Write-Host "No Macrium backup found in F:\win11recovery or F:\windows11recovery" -ForegroundColor Red
            return
        }
        Write-Warning ("macres: no first-span (-00-00) file found; restoring the newest available image: {0}" -f $fallback[0].FullName)
        $latest = $fallback[0]
    }
    else {
        $latest = $entryPoints | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    }

    Write-Host "Restoring: $($latest.FullName)" -ForegroundColor Cyan
    & $mrauto -r $latest.FullName --nowarning --quiet --wait
    Write-Host "Restore complete. Rebooting..." -ForegroundColor Green
    reboot
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'macres' @args
}
