# Generated by 2sc from function 'macres' (2026-08-12 12:36:39).
function macres {
    $latest = (Get-ChildItem "F:\win11recovery\*.mrimgx","F:\win11recovery\*.mrimg" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
    if (-not $latest) { Write-Host "No backup found in F:\win11recovery\" -ForegroundColor Red; return }
    Write-Host "Restoring: $latest" -ForegroundColor Cyan
    & F:\backup\windowsapps\installed\reflect\mrauto.exe -r "$latest" --nowarning --quiet --wait
    Write-Host "Restore complete. Rebooting..." -ForegroundColor Green
    reboot
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'macres' @args
}
