# Generated by 2sc from function 'macback' (2026-08-12 12:28:57).
# Hardened for cross-boot (Windows + Macrium Reflect WinPE/ISO) restore.
function macback {
[CmdletBinding()]
    param(
        [ValidateRange(1, 5)]
        [int] $MaxAttempts = 3,

        [ValidateRange(1, 300)]
        [int] $RetryDelaySeconds = 15,

        [ValidateRange(1, 10)]
        [int] $ProgressIntervalSeconds = 1,

        # Canonical recovery folder. Keep this ONE value as the single source
        # of truth; rmback and macres use the same folder. The rescue media
        # assigns its own drive letters, so a short, recognizable folder name
        # makes the backup easy to spot from the ISO.
        [string] $Destination = 'F:\win11recovery',

        # mrauto.exe is the Macrium command line automation binary.
        [string] $MrautoPath = 'F:\backup\windowsapps\installed\reflect\mrauto.exe'
    )

    $ErrorActionPreference = 'Stop'
    $sourceVolume = 'C:'
    $macriumLogRoot = 'C:\ProgramData\Macrium\Reflect'
    $progressId = 971

    # Resolve the drive letter from the destination so we validate the correct
    # volume regardless of how the folder path is spelled.
    $destinationDriveLetter = ([System.IO.Path]::GetPathRoot($Destination)).TrimEnd('\\')
    if (-not $destinationDriveLetter -or $destinationDriveLetter.Length -ne 2 -or $destinationDriveLetter[1] -ne ':') {
        throw "macback: invalid destination path: $Destination"
    }

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'macback requires an elevated Windows PowerShell 5.1 session because Macrium MRAuto and VSS require administrator privileges.'
    }
    if (-not (Test-Path -LiteralPath $MrautoPath -PathType Leaf)) {
        throw "macback cannot find Macrium MRAuto: $MrautoPath"
    }
    if (-not (Test-Path -LiteralPath ($destinationDriveLetter + '\') -PathType Container)) {
        throw "macback destination drive $destinationDriveLetter is not available."
    }
    if (-not (Test-Path -LiteralPath $Destination -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $Destination -Force
    }

    # Remove leftover artifacts from interrupted runs so the recovery folder
    # presents only valid images to the ISO/rescue media. Never touch files
    # while a Macrium imaging process is active.
    if (-not (Get-Process -Name 'mrauto','Reflect','ReflectBin','ReflectUI','ReflectMonitor' -ErrorAction SilentlyContinue)) {
        Get-ChildItem -LiteralPath $Destination -File -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -eq 'backup_running' -or $_.Extension -eq '.tmp' } |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
    $destinationDrive = New-Object System.IO.DriveInfo($destinationDriveLetter[0].ToString())
    if (-not $destinationDrive.IsReady) {
        throw "macback destination drive $destinationDriveLetter is not ready."
    }
    $latestExisting = Get-ChildItem -LiteralPath $Destination -Filter '*.mrimgx' -File -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    $minimumFreeBytes = 20GB
    if ($latestExisting -and ([double]$latestExisting.Length * 1.25) -gt $minimumFreeBytes) {
        $minimumFreeBytes = [int64]([double]$latestExisting.Length * 1.25)
    }
    if ($destinationDrive.AvailableFreeSpace -lt $minimumFreeBytes) {
        throw ("macback needs at least {0:N2} GiB free on {1}: based on the latest image size; only {2:N2} GiB is available." -f ($minimumFreeBytes / 1GB), $destinationDriveLetter, ($destinationDrive.AvailableFreeSpace / 1GB))
    }

    foreach ($serviceName in @('VSS', 'swprv')) {
        $serviceInfo = Get-CimInstance Win32_Service -Filter ("Name='{0}'" -f $serviceName)
        if ($null -eq $serviceInfo) {
            throw "macback cannot find required service '$serviceName'."
        }
        if ($serviceInfo.StartMode -eq 'Disabled') {
            Set-Service -Name $serviceName -StartupType Manual
        }
    }
    foreach ($serviceName in @('swprv', 'VSS')) {
        $service = Get-Service -Name $serviceName
        if ($service.Status -ne 'Running') {
            Start-Service -Name $serviceName
            $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))
        }
    }

    $lastLog = $null
    $lastDetail = $null
    $lastProcessExitCode = $null

    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        $attemptStarted = Get-Date
        $backupName = 'backup_{0}' -f $attemptStarted.ToString('yyyyMMdd_HHmmss')
        $stdoutPath = Join-Path $env:TEMP ("macback-{0}-{1}.stdout.log" -f $PID, [guid]::NewGuid().ToString('N'))
        $stderrPath = Join-Path $env:TEMP ("macback-{0}-{1}.stderr.log" -f $PID, [guid]::NewGuid().ToString('N'))
        $process = $null
        $stdoutText = ''
        $stderrText = ''
        $lastPercent = -1

        try {
            Write-Host ("macback: attempt {0}/{1}; source={2}; destination={3}; verify=enabled" -f $attempt, $MaxAttempts, $sourceVolume, $Destination) -ForegroundColor Cyan
            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status '0% - starting' -PercentComplete 0

            $argumentList = @('-b', $Destination, $backupName, $sourceVolume, '--wait', '--verify', '--stealth')
            $process = Start-Process -FilePath $MrautoPath -ArgumentList $argumentList -NoNewWindow -PassThru -RedirectStandardOutput $stdoutPath -RedirectStandardError $stderrPath

            while (-not $process.HasExited) {
                Start-Sleep -Seconds $ProgressIntervalSeconds
                $process.Refresh()

                if (Test-Path -LiteralPath $stdoutPath -PathType Leaf) {
                    $stream = [IO.File]::Open($stdoutPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
                    try {
                        $reader = New-Object IO.StreamReader($stream)
                        try { $stdoutText = $reader.ReadToEnd() } finally { $reader.Dispose() }
                    }
                    finally {
                        $stream.Dispose()
                    }
                }
                if (Test-Path -LiteralPath $stderrPath -PathType Leaf) {
                    $stream = [IO.File]::Open($stderrPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
                    try {
                        $reader = New-Object IO.StreamReader($stream)
                        try { $stderrText = $reader.ReadToEnd() } finally { $reader.Dispose() }
                    }
                    finally {
                        $stream.Dispose()
                    }
                }

                $combinedProgressText = $stdoutText + "`n" + $stderrText
                $progressMatches = [regex]::Matches($combinedProgressText, '(?i)Overall Progress:\s*(\d{1,3})%')
                $percent = 0
                $status = 'starting'
                if ($progressMatches.Count -gt 0) {
                    $percent = [Math]::Min(99, [int]$progressMatches[$progressMatches.Count - 1].Groups[1].Value)
                    $status = 'imaging'
                }
                elseif ($combinedProgressText -match '(?i)Verifying\s+[''"].*\.mrimgx') {
                    $percent = 90
                    $status = 'verifying image'
                }
                elseif ($combinedProgressText -match '(?i)Saving Partition') {
                    $percent = 10
                    $status = 'saving partition'
                }
                elseif ($combinedProgressText -match '(?i)Volume Snapshots Created') {
                    $percent = 7
                    $status = 'snapshot created'
                }
                elseif ($combinedProgressText -match '(?i)Creating Volume Snapshot') {
                    $percent = 4
                    $status = 'creating snapshot'
                }
                elseif ($combinedProgressText -match '(?i)Validation status\s*-\s*Ok') {
                    $percent = 2
                    $status = 'validated'
                }

                if ($percent -ne $lastPercent) {
                    Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status ("{0}% - {1}" -f $percent, $status) -PercentComplete $percent
                    $lastPercent = $percent
                }
            }

            $process.WaitForExit()
            $lastProcessExitCode = [int]$process.ExitCode
            if (Test-Path -LiteralPath $stdoutPath -PathType Leaf) {
                $stdoutText = [IO.File]::ReadAllText($stdoutPath)
            }
            if (Test-Path -LiteralPath $stderrPath -PathType Leaf) {
                $stderrText = [IO.File]::ReadAllText($stderrPath)
            }
        }
        finally {
            if ($process) {
                $process.Dispose()
            }
            Remove-Item -LiteralPath $stdoutPath -Force -ErrorAction SilentlyContinue
            Remove-Item -LiteralPath $stderrPath -Force -ErrorAction SilentlyContinue
        }

        $image = Get-ChildItem -LiteralPath $Destination -Filter ($backupName + '-*.mrimgx') -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        $lastLog = Get-ChildItem -LiteralPath $macriumLogRoot -Filter ($backupName + '-*.html') -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        $logText = if ($lastLog) { [IO.File]::ReadAllText($lastLog.FullName) } else { '' }
        $combinedText = $stdoutText + "`n" + $stderrText + "`n" + $logText

        $logSucceeded = $logText -match '<Error>0</Error>' -and
            $logText -match '<Status>0</Status>' -and
            $logText -match 'Image and Verification Completed Successfully'
        $autoVerifyEnabled = $combinedText -match '(?im)^Auto Verify:\s+Y\s*$' -or
            $logText -match '(?is)Auto Verify:.*?>Y<'
        $success = $lastProcessExitCode -eq 0 -and $image -and $image.Length -gt 0 -and $logSucceeded -and $autoVerifyEnabled

        if ($success) {
            # The image must be a complete, contiguous span set. mrauto names
            # spans name-00-00.mrimgx, name-00-01.mrimgx, ... The rescue media
            # restores from the FIRST span (-00-00), so confirm it exists and
            # that no span is missing in the middle of the set.
            $spans = @(Get-ChildItem -LiteralPath $Destination -Filter ($backupName + '-*.mrimgx') -File -ErrorAction SilentlyContinue |
                Sort-Object Name)
            if ($spans.Count -eq 0) {
                throw 'macback: verification passed but no image span files were found.'
            }
            $firstSpan = $spans | Where-Object { $_.Name -match '-00-00\.mrimgx$' } | Select-Object -First 1
            if (-not $firstSpan -or $firstSpan.Length -le 0) {
                throw ('macback: verification passed but the first image span (-00-00) is missing. Found: {0}' -f ($spans.Name -join ', '))
            }
            $firstSpans = @($spans | Where-Object { $_.Name -match '-00-00\.mrimgx$' })
            if ($firstSpans.Count -gt 1) {
                throw 'macback: multiple first-span (-00-00) files detected for one backup set; refusing to mark it complete.'
            }

            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status '100% - completed and verified' -PercentComplete 100
            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Completed
            Write-Host ("macback: 100% verified backup created: {0} ({1:N2} GiB)" -f $firstSpan.FullName, ($firstSpan.Length / 1GB)) -ForegroundColor Green

            # Persist a backup definition next to the image so Reflect (Windows
            # AND the WinPE rescue media) can import the set with one click and
            # so the "Existing Backups" list can locate it after a reboot.
            $definitionXml = Join-Path $macriumLogRoot 'mrauto_backup.xml'
            $definitionCopy = Join-Path $Destination 'Macrium_Backup_Definition.xml'
            try {
                if (Test-Path -LiteralPath $definitionXml -PathType Leaf) {
                    Copy-Item -LiteralPath $definitionXml -Destination $definitionCopy -Force -ErrorAction Stop
                    Write-Host ("macback: backup definition copied to {0}" -f $definitionCopy) -ForegroundColor DarkCyan
                }
            }
            catch {
                Write-Warning ("macback: could not copy the backup definition to the recovery folder: {0}" -f $_.Exception.Message)
            }

            # Make the backup discoverable from the WinPE/ISO rescue media: the
            # rescue environment reads the Recent Folders registry entries (and
            # the definition <directory>) at boot. Store the stable volume GUID
            # path there so the image is found even when WinPE assigns a
            # different drive letter than Windows.
            Set-MacriumRecoveryDiscovery -Destination $Destination -DriveLetter $destinationDriveLetter

            # Make the recovery folder self-describing so the backup is easy to
            # find from the ISO, where the drive letter is different.
            $volumeLabel = try {
                (Get-WmiObject Win32_Volume -Filter ("DriveLetter='{0}'" -f $destinationDriveLetter) -ErrorAction Stop | Select-Object -First 1).Label
            } catch { '' }
            if ([string]::IsNullOrWhiteSpace([string]$volumeLabel)) { $volumeLabel = '(no label)' }
            $readmePath = Join-Path $Destination '_README_RESTORE.txt'
            @(
                'MACRIUM REFLECT RECOVERY FOLDER'
                ('Latest verified backup: {0}' -f $firstSpan.Name)
                ('Size: {0:N2} GiB | Created: {1:yyyy-MM-dd HH:mm:ss}' -f ($firstSpan.Length / 1GB), $firstSpan.CreationTime)
                ('Backup definition: {0}' -f 'Macrium_Backup_Definition.xml')
                ('Volume label (Windows): {0}' -f $volumeLabel)
                ''
                'RESTORE FROM THE ISO WITHOUT WINDOWS:'
                '  1. Boot the Macrium Reflect rescue media / repair ISO.'
                '  2. In Reflect, open Restore > "Browse for an image file..."'
                '  3. Find this volume by its label (see above) or by its size,'
                '     then open the win11recovery folder.'
                '  4. Select the "-00-00.mrimgx" file (or the backup definition'
                '     XML) and restore to the target disk.'
                '  NOTE: the drive letter changes in WinPE (F: in Windows will'
                '        not be F: there). Look for the volume label, not F:.'
                '  CLI equivalent (from Windows): mrauto.exe -r "<image file>" --nowarning --quiet --wait'
            ) | Set-Content -LiteralPath $readmePath -Encoding ASCII

            return [pscustomobject]@{
                Status = 'Success'
                Verified = $true
                Attempts = $attempt
                ImagePath = $firstSpan.FullName
                SpanCount = $spans.Count
                SizeGiB = [math]::Round($firstSpan.Length / 1GB, 2)
                Created = $firstSpan.CreationTime
                Completed = $firstSpan.LastWriteTime
                MacriumLog = $lastLog.FullName
                ExitCode = $lastProcessExitCode
                DefinitionXml = $definitionCopy
            }
        }

        Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Completed
        if ($combinedText -match '(?is)(Backup aborted!.*?)(?:<|\r|\n|$)') {
            $lastDetail = ($matches[1] -replace '<[^>]+>', ' ').Trim()
        }
        elseif ($stderrText.Trim()) {
            $lastDetail = $stderrText.Trim()
        }
        else {
            $lastDetail = 'Macrium did not produce a verified-success result.'
        }

        $isVssFailure = $combinedText -match '(?i)0x80042302|0x80070422|VSS_E_BAD_STATE|Failed To Create Volume Snapshot'
        Write-Warning ("macback attempt {0} failed; exitCode={1}; vssFailure={2}; log={3}; detail={4}" -f $attempt, $lastProcessExitCode, $isVssFailure, $(if ($lastLog) { $lastLog.FullName } else { '<none>' }), $lastDetail)

        if ($attempt -lt $MaxAttempts) {
            foreach ($serviceName in @('VSS', 'swprv')) {
                Set-Service -Name $serviceName -StartupType Manual
            }
            foreach ($serviceName in @('swprv', 'VSS')) {
                $service = Get-Service -Name $serviceName
                if ($service.Status -ne 'Running') {
                    Start-Service -Name $serviceName
                    $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))
                }
            }
            Start-Sleep -Seconds $RetryDelaySeconds
        }
    }

    throw ("macback failed after {0} attempt(s). Last exit code: {1}. Last Macrium log: {2}. Detail: {3}" -f $MaxAttempts, $lastProcessExitCode, $(if ($lastLog) { $lastLog.FullName } else { '<none>' }), $lastDetail)
}

# Populate the Macrium rescue-media discovery state so the WinPE/ISO can find
# this backup without Windows. The rescue environment reads
# HKCU\SOFTWARE\Macrium\Reflect\Recent Folders\Image and \Backup at boot and
# searches the <directory> of the backup definition XML. Storing the stable
# volume GUID path (instead of a Windows-only drive letter) makes the image
# resolvable regardless of the letter WinPE assigns to the volume.
function Set-MacriumRecoveryDiscovery {
[CmdletBinding()]
    param(
        [string]$Destination,
        [string]$DriveLetter
    )

    $volumeGuid = $null
    try {
        $mountvolOutput = mountvol $DriveLetter /L 2>&1 | Out-String
        $match = [regex]::Match($mountvolOutput, 'Volume\{([0-9a-fA-F-]+)\}')
        if ($match.Success) { $volumeGuid = $match.Groups[1].Value }
    }
    catch { }

    $guidPath = $null
    if ($volumeGuid) {
        $folderName = $Destination.Substring(3).TrimStart('\')
        $guidPath = '\\?\Volume{' + $volumeGuid + '}\' + $folderName + '\'
    }

    $definitionXml = 'C:\ProgramData\Macrium\Reflect\mrauto_backup.xml'
    $definitionCopy = Join-Path $Destination 'Macrium_Backup_Definition.xml'
    foreach ($xml in @($definitionXml, $definitionCopy)) {
        if (-not (Test-Path -LiteralPath $xml -PathType Leaf)) { continue }
        try {
            $text = [IO.File]::ReadAllText($xml)
            $replacement = if ($guidPath) { $guidPath } else { $Destination + '\' }
            $newText = $text -replace '<directory>[^<]*</directory>', ('<directory>' + $replacement + '</directory>')
            if ($newText -ne $text) {
                [IO.File]::WriteAllText($xml, $newText)
            }
        }
        catch {
            Write-Warning ('macback: could not rewrite backup definition {0}: {1}' -f $xml, $_.Exception.Message)
        }
    }

    foreach ($folderType in @('Image', 'Backup')) {
        try {
            $key = 'HKCU:\SOFTWARE\Macrium\Reflect\Recent Folders\' + $folderType
            if (-not (Test-Path $key)) { New-Item -Path $key -Force | Out-Null }
            if ($guidPath) {
                New-ItemProperty -Path $key -Name '0' -Value $guidPath -PropertyType String -Force | Out-Null
            }
            New-ItemProperty -Path $key -Name '1' -Value ($Destination + '\') -PropertyType String -Force | Out-Null
        }
        catch {
            Write-Warning ('macback: could not update Recent Folders\{0}: {1}' -f $folderType, $_.Exception.Message)
        }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'macback' @args
}
