# Generated by 2sc from function 'macback' (2026-08-12 12:28:57).
function macback {
[CmdletBinding()]
    param(
        [ValidateRange(1, 5)]
        [int] $MaxAttempts = 3,

        [ValidateRange(1, 300)]
        [int] $RetryDelaySeconds = 15,

        [ValidateRange(1, 10)]
        [int] $ProgressIntervalSeconds = 1
    )

    $ErrorActionPreference = 'Stop'
    $mrauto = 'F:\backup\windowsapps\installed\reflect\mrauto.exe'
    $destination = 'F:\win11recovery'
    $sourceVolume = 'C:'
    $macriumLogRoot = 'C:\ProgramData\Macrium\Reflect'
    $progressId = 971

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'macback requires an elevated Windows PowerShell 5.1 session because Macrium MRAuto and VSS require administrator privileges.'
    }
    if (-not (Test-Path -LiteralPath $mrauto -PathType Leaf)) {
        throw "macback cannot find Macrium MRAuto: $mrauto"
    }
    if (-not (Test-Path -LiteralPath 'F:\' -PathType Container)) {
        throw 'macback destination drive F: is not available.'
    }
    if (-not (Test-Path -LiteralPath $destination -PathType Container)) {
        $null = New-Item -ItemType Directory -Path $destination -Force
    }

    # Remove leftover artifacts from interrupted runs so the recovery folder
    # presents only valid images to the ISO/rescue media. Never touch files
    # while a Macrium imaging process is active.
    if (-not (Get-Process -Name 'mrauto','Reflect','ReflectBin','ReflectUI','ReflectMonitor' -ErrorAction SilentlyContinue)) {
        Get-ChildItem -LiteralPath $destination -File -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -eq 'backup_running' -or $_.Extension -eq '.tmp' } |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
    $destinationDrive = New-Object System.IO.DriveInfo('F')
    if (-not $destinationDrive.IsReady) {
        throw 'macback destination drive F: is not ready.'
    }
    $latestExisting = Get-ChildItem -LiteralPath $destination -Filter '*.mrimgx' -File -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    $minimumFreeBytes = 20GB
    if ($latestExisting -and ([double]$latestExisting.Length * 1.25) -gt $minimumFreeBytes) {
        $minimumFreeBytes = [int64]([double]$latestExisting.Length * 1.25)
    }
    if ($destinationDrive.AvailableFreeSpace -lt $minimumFreeBytes) {
        throw ("macback needs at least {0:N2} GiB free on F: based on the latest image size; only {1:N2} GiB is available." -f ($minimumFreeBytes / 1GB), ($destinationDrive.AvailableFreeSpace / 1GB))
    }

    foreach ($serviceName in @('VSS', 'swprv')) {
        $serviceInfo = Get-CimInstance Win32_Service -Filter ("Name='{0}'" -f $serviceName)
        if ($null -eq $serviceInfo) {
            throw "macback cannot find required service '$serviceName'."
        }
        if ($serviceInfo.StartMode -eq 'Disabled') {
            Set-Service -Name $serviceName -StartupType Manual
        }
    }
    foreach ($serviceName in @('swprv', 'VSS')) {
        $service = Get-Service -Name $serviceName
        if ($service.Status -ne 'Running') {
            Start-Service -Name $serviceName
            $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))
        }
    }

    $lastLog = $null
    $lastDetail = $null
    $lastProcessExitCode = $null

    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        $attemptStarted = Get-Date
        $backupName = 'backup_{0}' -f $attemptStarted.ToString('yyyyMMdd_HHmmss')
        $stdoutPath = Join-Path $env:TEMP ("macback-{0}-{1}.stdout.log" -f $PID, [guid]::NewGuid().ToString('N'))
        $stderrPath = Join-Path $env:TEMP ("macback-{0}-{1}.stderr.log" -f $PID, [guid]::NewGuid().ToString('N'))
        $process = $null
        $stdoutText = ''
        $stderrText = ''
        $lastPercent = -1

        try {
            Write-Host ("macback: attempt {0}/{1}; source={2}; destination={3}; verify=enabled" -f $attempt, $MaxAttempts, $sourceVolume, $destination) -ForegroundColor Cyan
            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status '0% - starting' -PercentComplete 0

            $argumentList = @('-b', $destination, $backupName, $sourceVolume, '--wait', '--verify', '--stealth')
            $process = Start-Process -FilePath $mrauto -ArgumentList $argumentList -NoNewWindow -PassThru -RedirectStandardOutput $stdoutPath -RedirectStandardError $stderrPath

            while (-not $process.HasExited) {
                Start-Sleep -Seconds $ProgressIntervalSeconds
                $process.Refresh()

                if (Test-Path -LiteralPath $stdoutPath -PathType Leaf) {
                    $stream = [IO.File]::Open($stdoutPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
                    try {
                        $reader = New-Object IO.StreamReader($stream)
                        try { $stdoutText = $reader.ReadToEnd() } finally { $reader.Dispose() }
                    }
                    finally {
                        $stream.Dispose()
                    }
                }
                if (Test-Path -LiteralPath $stderrPath -PathType Leaf) {
                    $stream = [IO.File]::Open($stderrPath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
                    try {
                        $reader = New-Object IO.StreamReader($stream)
                        try { $stderrText = $reader.ReadToEnd() } finally { $reader.Dispose() }
                    }
                    finally {
                        $stream.Dispose()
                    }
                }

                $combinedProgressText = $stdoutText + "`n" + $stderrText
                $progressMatches = [regex]::Matches($combinedProgressText, '(?i)Overall Progress:\s*(\d{1,3})%')
                $percent = 0
                $status = 'starting'
                if ($progressMatches.Count -gt 0) {
                    $percent = [Math]::Min(99, [int]$progressMatches[$progressMatches.Count - 1].Groups[1].Value)
                    $status = 'imaging'
                }
                elseif ($combinedProgressText -match '(?i)Verifying\s+[''"].*\.mrimgx') {
                    $percent = 90
                    $status = 'verifying image'
                }
                elseif ($combinedProgressText -match '(?i)Saving Partition') {
                    $percent = 10
                    $status = 'saving partition'
                }
                elseif ($combinedProgressText -match '(?i)Volume Snapshots Created') {
                    $percent = 7
                    $status = 'snapshot created'
                }
                elseif ($combinedProgressText -match '(?i)Creating Volume Snapshot') {
                    $percent = 4
                    $status = 'creating snapshot'
                }
                elseif ($combinedProgressText -match '(?i)Validation status\s*-\s*Ok') {
                    $percent = 2
                    $status = 'validated'
                }

                if ($percent -ne $lastPercent) {
                    Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status ("{0}% - {1}" -f $percent, $status) -PercentComplete $percent
                    $lastPercent = $percent
                }
            }

            $process.WaitForExit()
            $lastProcessExitCode = [int]$process.ExitCode
            if (Test-Path -LiteralPath $stdoutPath -PathType Leaf) {
                $stdoutText = [IO.File]::ReadAllText($stdoutPath)
            }
            if (Test-Path -LiteralPath $stderrPath -PathType Leaf) {
                $stderrText = [IO.File]::ReadAllText($stderrPath)
            }
        }
        finally {
            if ($process) {
                $process.Dispose()
            }
            Remove-Item -LiteralPath $stdoutPath -Force -ErrorAction SilentlyContinue
            Remove-Item -LiteralPath $stderrPath -Force -ErrorAction SilentlyContinue
        }

        $image = Get-ChildItem -LiteralPath $destination -Filter ($backupName + '-*.mrimgx') -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        $lastLog = Get-ChildItem -LiteralPath $macriumLogRoot -Filter ($backupName + '-*.html') -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        $logText = if ($lastLog) { [IO.File]::ReadAllText($lastLog.FullName) } else { '' }
        $combinedText = $stdoutText + "`n" + $stderrText + "`n" + $logText

        $logSucceeded = $logText -match '<Error>0</Error>' -and
            $logText -match '<Status>0</Status>' -and
            $logText -match 'Image and Verification Completed Successfully'
        $autoVerifyEnabled = $combinedText -match '(?im)^Auto Verify:\s+Y\s*$' -or
            $logText -match '(?is)Auto Verify:.*?>Y<'
        $success = $lastProcessExitCode -eq 0 -and $image -and $image.Length -gt 0 -and $logSucceeded -and $autoVerifyEnabled

        if ($success) {
            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Status '100% - completed and verified' -PercentComplete 100
            Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Completed
            Write-Host ("macback: 100% verified backup created: {0} ({1:N2} GiB)" -f $image.FullName, ($image.Length / 1GB)) -ForegroundColor Green
            $readmePath = Join-Path $destination '_README_RESTORE.txt'
            @(
                'MACRIUM REFLECT RECOVERY FOLDER'
                ('Latest verified backup: {0}' -f $image.Name)
                ('Size: {0:N2} GiB | Created: {1:yyyy-MM-dd HH:mm:ss}' -f ($image.Length / 1GB), $image.CreationTime)
                'RESTORE FROM THE ISO WITHOUT WINDOWS:'
                '  1. Boot the Macrium Reflect rescue media / repair ISO.',
                '  2. In Reflect, open the image file named above from this folder.',
                '     The drive letter may differ in WinPE; look for the volume that has win11recovery.',
                '  3. Restore it to the target disk/partitions and confirm.',
                '  CLI equivalent: mrauto.exe -r "F:\win11recovery\<image file>" --nowarning --quiet --wait'
            ) | Set-Content -LiteralPath $readmePath -Encoding ASCII
            return [pscustomobject]@{
                Status = 'Success'
                Verified = $true
                Attempts = $attempt
                ImagePath = $image.FullName
                SizeGiB = [math]::Round($image.Length / 1GB, 2)
                Created = $image.CreationTime
                Completed = $image.LastWriteTime
                MacriumLog = $lastLog.FullName
                ExitCode = $lastProcessExitCode
            }
        }

        Write-Progress -Id $progressId -Activity 'Macrium backup and verification' -Completed
        if ($combinedText -match '(?is)(Backup aborted!.*?)(?:<|\r|\n|$)') {
            $lastDetail = ($matches[1] -replace '<[^>]+>', ' ').Trim()
        }
        elseif ($stderrText.Trim()) {
            $lastDetail = $stderrText.Trim()
        }
        else {
            $lastDetail = 'Macrium did not produce a verified-success result.'
        }

        $isVssFailure = $combinedText -match '(?i)0x80042302|0x80070422|VSS_E_BAD_STATE|Failed To Create Volume Snapshot'
        Write-Warning ("macback attempt {0} failed; exitCode={1}; vssFailure={2}; log={3}; detail={4}" -f $attempt, $lastProcessExitCode, $isVssFailure, $(if ($lastLog) { $lastLog.FullName } else { '<none>' }), $lastDetail)

        if ($attempt -lt $MaxAttempts) {
            foreach ($serviceName in @('VSS', 'swprv')) {
                Set-Service -Name $serviceName -StartupType Manual
            }
            foreach ($serviceName in @('swprv', 'VSS')) {
                $service = Get-Service -Name $serviceName
                if ($service.Status -ne 'Running') {
                    Start-Service -Name $serviceName
                    $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))
                }
            }
            Start-Sleep -Seconds $RetryDelaySeconds
        }
    }

    throw ("macback failed after {0} attempt(s). Last exit code: {1}. Last Macrium log: {2}. Detail: {3}" -f $MaxAttempts, $lastProcessExitCode, $(if ($lastLog) { $lastLog.FullName } else { '<none>' }), $lastDetail)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'macback' @args
}
