# Generated by 2sc from function 'rmback' (2026-08-12 12:35:11).
# Hardened: uses the same canonical recovery folder as macback.
function rmback {
[CmdletBinding()]
    param(
        [switch] $PlanOnly,

        [ValidateRange(1, 5)]
        [int] $MaxAttempts = 3,

        [ValidateRange(1, 300)]
        [int] $RetryDelaySeconds = 15,

        # Canonical recovery folder (single source of truth shared with macback).
        [string] $BackupDirectory = 'F:\win11recovery'
    )

    $ErrorActionPreference = 'Stop'
    $progressId = 972

    if (-not (Test-Path -LiteralPath $BackupDirectory -PathType Container)) {
        throw "RMBACK: backup directory was not found: $BackupDirectory"
    }

    # Remove leftover artifacts from interrupted runs so the recovery folder
    # presents only valid images to the ISO/rescue media.
    if (-not (Get-Process -Name 'mrauto','Reflect','ReflectBin','ReflectUI','ReflectMonitor' -ErrorAction SilentlyContinue)) {
        Get-ChildItem -LiteralPath $BackupDirectory -File -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -eq 'backup_running' -or $_.Extension -eq '.tmp' } |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
    $existingBackups = @(Get-ChildItem -LiteralPath $BackupDirectory -Filter '*.mrimgx' -File -Force -ErrorAction SilentlyContinue)
    if ($PlanOnly) {
        Write-Output ("RMBACK_PLAN backup_directory=""{0}"" existing_backups={1}" -f $BackupDirectory, $existingBackups.Count)
        return
    }

    $started = Get-Date
    Write-Host ("rmback: creating and verifying a new backup; existing backups={0}" -f $existingBackups.Count) -ForegroundColor Cyan
    $result = macback -Destination $BackupDirectory -MaxAttempts $MaxAttempts -RetryDelaySeconds $RetryDelaySeconds

    if ($null -eq $result -or $result.Status -ne 'Success' -or -not $result.Verified -or [string]::IsNullOrWhiteSpace([string]$result.ImagePath)) {
        throw 'RMBACK: macback did not return a verified-success result; no existing backup files were deleted.'
    }

    $newBackup = Get-Item -LiteralPath ([string]$result.ImagePath) -ErrorAction Stop
    $resolvedDirectory = [IO.Path]::GetFullPath($BackupDirectory).TrimEnd('\\')
    $resolvedNewBackup = [IO.Path]::GetFullPath($newBackup.FullName)
    if ([IO.Path]::GetDirectoryName($resolvedNewBackup).TrimEnd('\\') -ne $resolvedDirectory -or $newBackup.Extension -ne '.mrimgx' -or $newBackup.Length -le 0) {
        throw 'RMBACK: macback returned an invalid backup path; no existing backup files were deleted.'
    }

    $newerBackup = Get-ChildItem -LiteralPath $BackupDirectory -Filter '*.mrimgx' -File -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -ne $newBackup.FullName -and $_.CreationTime -gt $newBackup.CreationTime } |
        Select-Object -First 1
    if ($newerBackup) {
        throw "RMBACK: a newer backup appeared concurrently: $($newerBackup.FullName); no backup files were deleted."
    }

    $olderBackups = @(Get-ChildItem -LiteralPath $BackupDirectory -Filter '*.mrimgx' -File -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -ne $newBackup.FullName })

    $deleteFailures = @()
    for ($index = 0; $index -lt $olderBackups.Count; $index++) {
        $oldBackup = $olderBackups[$index]
        $resolvedOldBackup = [IO.Path]::GetFullPath($oldBackup.FullName)
        if ([IO.Path]::GetDirectoryName($resolvedOldBackup).TrimEnd('\\') -ne $resolvedDirectory -or $oldBackup.Extension -ne '.mrimgx') {
            $deleteFailures += $oldBackup.FullName
            continue
        }

        $percent = [int](100 * ($index + 1) / $olderBackups.Count)
        Write-Progress -Id $progressId -Activity 'Removing older Macrium backups' -Status ("{0}% - deleting {1}" -f $percent, $oldBackup.Name) -PercentComplete $percent
        try {
            Remove-Item -LiteralPath $resolvedOldBackup -Force -ErrorAction Stop
            if (Test-Path -LiteralPath $resolvedOldBackup) {
                throw 'The backup file still exists after Remove-Item completed.'
            }
        }
        catch {
            $deleteFailures += $oldBackup.FullName
        }
    }
    Write-Progress -Id $progressId -Activity 'Removing older Macrium backups' -Completed

    if ($deleteFailures.Count -gt 0) {
        throw ("RMBACK: kept the verified newest backup but could not delete {0} older backup(s): {1}" -f $deleteFailures.Count, ($deleteFailures -join '; '))
    }

    Write-Host ("rmback: 100% complete; kept {0}; force-deleted {1} older backup(s)." -f $newBackup.FullName, $olderBackups.Count) -ForegroundColor Green
    return [pscustomobject]@{
        Status = 'Success'
        Verified = $true
        Kept = $newBackup.FullName
        Deleted = $olderBackups.Count
        ElapsedSeconds = [math]::Round(((Get-Date) - $started).TotalSeconds, 2)
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'rmback' @args
}
